export interface Achiever {
  id: number;
  name: string;
  batch: string;
  role: string;
  exrole?: string;
  achievements?: string;
  image: string;
  linkedin: string;
}

export const achieversData: Achiever[] = [
  {
    id: 1,
    name: "Raman",
    batch: "2020-24",
    role: "Full Stack Developer at Styli",
    exrole: "Wiingy, GRNConnect, Ingenium",
    image: "/assets/team-photos/24 Batch/Raman.jpg",
    linkedin: "https://www.linkedin.com/in/raman-sde1/",
  },
  {
    id: 2,
    name: "Siddhant Vijay Singh",
    batch: "2020-24",
    role: "Application Developer 1 at NCR Atleos",
    exrole: "DevOps Intern at Infrasity and SWE Intern at HyperSpace",
    image: "/assets/team-photos/24 Batch/Siddhant.jpg",
    linkedin: "https://www.linkedin.com/in/sidvjsingh/",
  },
  {
    id: 3,
    name: "Ayush Garg",
    batch: "2020-24",
    role: "APM at PW",
    exrole: "LawSikho, Narra8ive",
    achievements: "Former President at Anveshan",
    image: "/assets/team-photos/24 Batch/Ayush_Garg.png",
    linkedin: "https://www.linkedin.com/in/gargayush909/",
  },
  {
    id: 4,
    name: "Ayush Saini",
    batch: "2020-24",
    role: "DBA at Bachtel India",
    exrole: "Web Developer Intern at Bechtel India",
    achievements: "Former Vice President at Anveshan",
    image: "/assets/team-photos/24 Batch/Ayush_S.jpg",
    linkedin: "https://www.linkedin.com/in/ayush-saini-09686b217/",
  },
  {
    id: 5,
    name: "Manav Garg",
    batch: "2020-24",
    role: "Data Analyst at Internshala",
    exrole: "Data Analyst Intern at Pristyn Care",
    image: "/assets/team-photos/24 Batch/Manav.jpg",
    linkedin: "https://www.linkedin.com/in/manav-garg04/",
  },
  {
    id: 6,
    name: "Harshit Sharma",
    batch: "2020-24",
    role: "Data Analyst at Genpact",
    exrole: "Data Analyst Intern at Sparks Foundation",
    image: "/assets/team-photos/24 Batch/Harshit.jpg",
    linkedin: "https://www.linkedin.com/in/harshit-sharma-hsh/",
  },
  {
    id: 7,
    name: "Sumit Kumar",
    batch: "2020-24",
    role: "SDE(Android) at Yulu",
    exrole: "Raaho, PowerhouseAI, Ingenium",
    image: "/assets/team-photos/24 Batch/Sumit.jpg",
    linkedin: "https://www.linkedin.com/in/stkrr002/",
  },
  {
    id: 8,
    name: "Mayank Nailwal",
    batch: "2021-25",
    role: "SDE-1 (Android) at Rooter.gg",
    exrole: "iOS developer Intern at Mobilicis",
    achievements: "Former President at Anveshan",
    image: "/assets/team-photos/25 Batch/Mayank.jpg",
    linkedin: "https://www.linkedin.com/in/mayanktech/",
  },
  {
    id: 9,
    name: "Udish Rawal",
    batch: "2021-25",
    role: "Flutter Developer Intern at Petro IT Solutions",
    achievements: "Former Vice President at Anveshan",
    image: "/assets/team-photos/25 Batch/Udish.png",
    linkedin: "https://www.linkedin.com/in/udish-rawal-a911a9268/",
  },
  {
    id: 10,
    name: "Tushar Sethi",
    batch: "2021-25",
    role: "ASE at Accenture",
    exrole: "Blue Planet, Coding Blocks",
    achievements: "Former Secretary at Anveshan",
    image: "/assets/team-photos/25 Batch/Tushar.png",
    linkedin: "https://www.linkedin.com/in/tushar-sethi-9342a722b/",
  },
  {
    id: 11,
    name: "Akanksha Mishra",
    batch: "2021-25",
    role: "Founder's Office Intern at Crossing Hurdles",
    exrole: "Database Intern at OM Info Solutions",
    achievements: "Former Social Media Head at Anveshan",
    image: "/assets/team-photos/25 Batch/Akanksha.jpg",
    linkedin: "https://www.linkedin.com/in/akanksha-mishra-120a95253/",
  },
  {
    id: 12,
    name: "Yash Verma",
    batch: "2021-25",
    role: "Full stack Developer at Finzarc",
    image: "/assets/team-photos/25 Batch/Yash.png",
    linkedin: "https://www.linkedin.com/in/yash-verma-5ba426333/",
  },
  {
    id: 13,
    name: "Aadish Jain",
    batch: "2022-26",
    role: "Backend Developer Trainee at PW",
    exrole: "SDE Intern at Appzlogic Mobility Solutions",
    achievements: "Former Vice President at Anveshan",
    image: "/assets/team-photos/26 Batch/Aadish.jpg",
    linkedin: "https://www.linkedin.com/in/aadishj23/",
  },
  {
    id: 14,
    name: "Kaushal Kumar Rai",
    batch: "2022-26",
    role: "React Intern at Sanskaar Group",
    exrole: "React Intern at Brainchant",
    achievements: "Winner at Kaizen'23",
    image: "/assets/team-photos/26 Batch/Kaushal.jpg",
    linkedin: "https://www.linkedin.com/in/kaushalrai007/",
  },
  {
    id: 15,
    name: "Tanay Kumar",
    batch: "2022-26",
    role: "Founding Engineer at FinalRound AI",
    exrole: "TraderMesh, Brainchant, Sanksaar group, ReferRush",
    image: "/assets/team-photos/26 Batch/Tanay.jpg",
    linkedin: "https://www.linkedin.com/in/tanaykmr/",
  },
  {
    id: 16,
    name: "Bhavishya Bhaskar",
    batch: "2022-26",
    role: "Expert @Codeforces",
    achievements: "Former DSA Head at Anveshan",
    image: "/assets/team-photos/26 Batch/Bhavishya.jpg",
    linkedin: "https://www.linkedin.com/in/bhavishya-bhaskar-084445260/",
  },
  {
    id: 17,
    name: "Raushan",
    batch: "2022-26",
    role: "UI/UX designer Intern at Twoward Technologies",
    exrole: "Tech Analyst at Tata Play Fibre",
    image: "/assets/team-photos/26 Batch/Raushan.jpg",
    linkedin: "https://www.linkedin.com/in/raushan-kumar-singh-31b6b8326/",
  },
  {
    id: 18,
    name: "Parth Nepalia",
    batch: "2022-26",
    role: "Software Engineer intern at Gocomet",
    achievements: "Former Vice President at Anveshan",
    image: "/assets/team-photos/26 Batch/Parth.jpg",
    linkedin: "https://www.linkedin.com/in/parth-nepalia0203/",
  },
  {
    id: 19,
    name: "Anamika Singh",
    batch: "2023-27",
    role: "Web Development Intern at Ada labs",
    achievements: "3+ Hackathon Winner",
    image: "/assets/team-photos/Senior Council/anamika.jpg",
    linkedin: "https://www.linkedin.com/in/anamikasingh20/",
  },
  {
    id: 20,
    name: "Karnita Saumya",
    batch: "2023-27",
    role: "Data Analyst Intern at IMVED technologies Pvt Ltd.",
    image: "/assets/team-photos/Senior Council/karnita.jpg",
    linkedin: "https://www.linkedin.com/in/karnita-saumya/",
  },
  {
    id: 21,
    name: "Astha Negi",
    batch: "2023-27",
    role: "Business Intelligence Engineer Intern at Amazon",
    image: "/assets/team-photos/Senior Council/astha.jpg",
    linkedin: "https://www.linkedin.com/in/astha-negi-90874b2b3/",
  },
];
