export interface TeamMember {
  id: number;
  name: string;
  position: string;
  category: "Senior Council" | "Junior Council";
  image: string;
  LinkedinLink?: string;
  GithubLink?: string;
  LeetcodeLink?: string;
  CodolioLink?: string;
  TwitterLink?: string;
  InstagramLink?: string;
}

/* =========================================================================
   LEGACY SENIOR COUNCIL (Preserved - Do Not Delete)
   =========================================================================
export const legacySeniorCouncil: TeamMember[] = [
  {
    id: 101,
    name: 'Anamika',
    position: 'President',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/anamika.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/anamikasingh20/',
    GithubLink: 'https://github.com/Anamiiikka',
    InstagramLink: 'https://www.instagram.com/yb_anamika/?hl=en',
  },
  {
    id: 102,
    name: 'Keshav',
    position: 'Vice President',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/keshav.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/keshav-mehra-543362296',
    GithubLink: 'https://github.com/Airbone25',
    InstagramLink:
      'https://www.instagram.com/theautisticone__?igsh=MXIzbmV0ZjhzOXgzbg==',
  },
  {
    id: 103,
    name: 'Vanshika',
    position: 'Vice President',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/vanshika.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/vanshika-tanwar-75b897297',
    GithubLink: 'https://github.com/Vanshika-Tanwar/',
    LeetcodeLink: 'https://leetcode.com/u/VanshikaTanwar/',
  },
  {
    id: 104,
    name: 'Drishti',
    position: 'Head of Operations',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/drishti.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/drishti-goel-27b897297/',
    GithubLink: 'https://github.com/drishtigoel083',
    TwitterLink: 'https://x.com/DrishtiGoe22413',
  },
  {
    id: 105,
    name: 'Astha',
    position: 'Secretary',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/astha.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/astha-negi-90874b2b3/',
    GithubLink: 'https://github.com/astha-negi',
    LeetcodeLink: 'https://leetcode.com/u/Astha_Negi/',
  },
  {
    id: 106,
    name: 'Shwet',
    position: 'Secretary',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/shwet.jpg',
    LinkedinLink: 'http://www.linkedin.com/in/shwet-kashyap-56179b289',
    GithubLink: 'https://github.com/SHWETKASHYAP',
    CodolioLink: 'https://codolio.com/profile/Shwetkashyap',
  },
  {
    id: 107,
    name: 'Preeti',
    position: 'Social Media Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/preeti.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/preeti-kumari-436731293',
    GithubLink: 'https://github.com/preetikumari15',
    LeetcodeLink: 'https://leetcode.com/u/Preetikumari15/',
  },
  {
    id: 108,
    name: 'Karnita',
    position: 'Social Media Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/karnita.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/karnita-saumya/',
    GithubLink: 'https://github.com/Karnita-Saumya',
  },
  {
    id: 109,
    name: 'Tanishq',
    position: 'Graphics Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/tanishq.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/tanishqbhadula/',
    GithubLink: 'https://github.com/tanishqbhadula',
  },
  {
    id: 110,
    name: 'Parth Sharma',
    position: 'Graphics Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/ParthSharma.jpeg',
    LinkedinLink: 'https://www.linkedin.com/in/parthsharma00/',
    GithubLink: 'https://github.com/parthsharma5575',
    InstagramLink: 'https://www.instagram.com/_.parthsharma.__/',
  },
  {
    id: 111,
    name: 'Mehak',
    position: 'PR Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/mehak.jpg',
    LinkedinLink:
      'https://www.linkedin.com/in/mehak-suri-3178602b4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
    InstagramLink:
      'https://www.instagram.com/mehak_surii?igsh=MTNyOWhlN2YzZGQxYw%3D%3D&utm_source=qr',
  },
  {
    id: 112,
    name: 'Vansh',
    position: 'DSA Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/vansh.webp',
    LinkedinLink: 'https://www.linkedin.com/in/vansh-ahuja-b3648b273/',
    GithubLink: 'https://github.com/vansh3175',
    LeetcodeLink: 'https://leetcode.com/u/vansh317/',
  },
  {
    id: 113,
    name: 'Sarthak',
    position: 'DSA Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/sarthak.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/sarthak-jain-93b875294',
    GithubLink: 'https://github.com/Sarthak-Jain18',
    LeetcodeLink: 'https://leetcode.com/u/sarthak_jain18/',
  },
  {
    id: 114,
    name: 'Riya',
    position: 'Web Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/riya.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/riya-v-7973782a1',
    GithubLink: 'https://github.com/verma-riya20',
    LeetcodeLink: 'https://leetcode.com/u/riyaverma12/',
  },
  {
    id: 115,
    name: 'Tanishq',
    position: 'Android Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/tanishq.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/tanishqbhadula/',
    GithubLink: 'https://github.com/tanishqbhadula',
  },
  {
    id: 116,
    name: 'Gaurav',
    position: 'CP Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/gaurav.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/gauravsingh640',
    CodolioLink: 'https://codolio.com/profile/Gaurav640',
    InstagramLink:
      'https://www.instagram.com/itsme_gaurav_rajput?igsh=cDg2NDdnejR0c2I=',
  },
  {
    id: 117,
    name: 'Dipesh',
    position: 'ML Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/dipesh.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/dipesh-lohchab/',
    GithubLink: 'https://github.com/dipeshlohchab',
    LeetcodeLink: 'https://leetcode.com/u/dipeshlohchab0302/',
  },
  {
    id: 118,
    name: 'Krishna',
    position: 'ML Head',
    category: 'Senior Council',
    image: '/assets/team-photos/Senior Council/krishna.jpg',
    LinkedinLink: 'https://www.linkedin.com/in/krishna-tyagi-/',
    GithubLink: 'https://github.com/knight22-21',
    LeetcodeLink: 'https://leetcode.com/u/knight22-21/',
  },
];
========================================================================= */

export const seniorCouncil: TeamMember[] = [
  {
    id: 1,
    name: "Garvit",
    position: "President",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/garvit.jpeg",
    LinkedinLink: "https://www.linkedin.com/in/garvit-",
    GithubLink: "https://github.com/garvit-arora",
    LeetcodeLink: "https://leetcode.com/u/garvit-",
  },
  {
    id: 2,
    name: "Nishtha",
    position: "Vice President",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/nishtha.png",
    LinkedinLink: "https://www.linkedin.com/in/nishtha-sood-53a75a306",
    GithubLink: "https://github.com/nishthaasood",
    InstagramLink: "https://www.instagram.com/nishthasood7",
  },
  {
    id: 3,
    name: "Aakriti",
    position: "Head of Operations & Graphics Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/aakriti.jpg",
    LinkedinLink: "https://www.linkedin.com/in/aakriti-arya/",
    GithubLink: "https://github.com/Aakriti0207",
    LeetcodeLink: "https://leetcode.com/u/AakritiArya/",
  },
  {
    id: 4,
    name: "Kaavy",
    position: "Secretary",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/kaavy.jpg",
    LinkedinLink: "https://www.linkedin.com/in/kaavy-aggarwal-15b639333",
    GithubLink: "https://github.com/kaavy05",
    LeetcodeLink: "https://leetcode.com/u/kaavy05/",
  },
   {
    id: 5,
    name: "Pallavi",
    position: "Web Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/pallavi.jpg",
    LinkedinLink: "https://www.linkedin.com/in/pallavi-jain-4b340032a",
    GithubLink: "https://github.com/pallavithegod",
    LeetcodeLink: "https://leetcode.com/u/code_pallavi/",
  },
  {
    id: 6,
    name: "Arshia",
    position: "DSA Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/arshia.jpg",
    LinkedinLink:
      "https://www.linkedin.com/in/arshia-gupta-ba4672284?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    GithubLink: "https://github.com/arshiagupta0807",
    LeetcodeLink: "https://leetcode.com/arshiagupta08/",
  },
  {
    id: 7,
    name: "Saiyam",
    position: "DSA Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/saiyam.jpg",
    LinkedinLink: "https://www.linkedin.com/in/saiyam-kumar-0b8933324/",
    GithubLink: "https://github.com/SaiyamKumar510",
    LeetcodeLink: "https://leetcode.com/u/Kumar_Saiyam/",
  },
  {
    id: 8,
    name: "Devansh",
    position: "ML Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/devansh.jpg",
    LinkedinLink: "https://www.linkedin.com/in/devansh-sharma-ba0a54302/",
    GithubLink: "https://github.com/Devansh865",
    InstagramLink: "https://www.instagram.com/devansh.26_/",
  },
  {
    id: 9,
    name: "Arpit",
    position: "ML Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/arpit_jindal.jpg",
    LinkedinLink: "https://www.linkedin.com/in/arpit-jindal-370434319/",
    GithubLink: "https://github.com/AJ914",
    LeetcodeLink: "https://leetcode.com/u/Arpitajrocks914/",
  },
  {
    id: 10,
    name: "Lakshay",
    position: "PR Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/lakshay.jpg",
    LinkedinLink:
      "https://www.linkedin.com/in/lakshay-dawar?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    LeetcodeLink: "https://leetcode.com/u/LakshayDawar/",
    TwitterLink: "https://x.com/LakshayINcode?t=EXGJF6cIA5GLXHAX1BLHlg&s=09",
  },
  {
    id: 11,
    name: "Vartika",
    position: "PR Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/vartika.jpg",
    LinkedinLink: "https://linkedin.com/in/vartika-sharma-5b3868325",
    GithubLink: "https://github.com/vartika6451",
    LeetcodeLink: "https://leetcode.com/u/vartika6451/",
  },
  {
    id: 12,
    name: "Prerna",
    position: "Social Media Head",
    category: "Senior Council",
    image: "/assets/team-photos/senior-council/prerna.jpeg",
    LinkedinLink:
      "https://www.linkedin.com/in/prerna-sharma-b3001b335?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    GithubLink: "https://github.com/prerna020",
    LeetcodeLink: "https://leetcode.com/u/PrernaS_20/",
  },
];

export const juniorCouncil: TeamMember[] = [
  {
    id: 13,
    name: "Aditya",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/aditya_sharma.jpg",
    LinkedinLink: "https://www.linkedin.com/in/sharma-aadi24",
    GithubLink: "https://github.com/sharma-aadi24",
    LeetcodeLink: "https://leetcode.com/sharma_aadi24/",
  },
  {
    id: 14,
    name: "Kirti",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/kirti_goyal.jpg",
    LinkedinLink: "https://www.linkedin.com/in/kirti-goyal-451870381",
    GithubLink: "https://github.com/kirtigoyal06",
    LeetcodeLink: "https://leetcode.com/u/Kirti_goyal108/",
  },
  {
    id: 15,
    name: "Bhavya",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/bhavya_gupta.jpg",
    LinkedinLink: "https://www.linkedin.com/in/bhavya-gupta-152512377/",
    GithubLink: "https://github.com/bhavya1701",
    LeetcodeLink: "https://leetcode.com/u/Bhavyagupta1701/",
  },
  {
    id: 16,
    name: "Manan",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/manan_jain.jpg",
    LinkedinLink: "https://www.linkedin.com/in/manan-jain-89a12937b",
    GithubLink: "https://github.com/Manajain20",
    LeetcodeLink: "https://leetcode.com/Mananjain_20",
  },
  {
    id: 17,
    name: "Laxmi",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/laxmi_kumari.jpg",
    LinkedinLink: "https://www.linkedin.com/in/laxmi-singh-377423303",
    GithubLink: "https://github.com/Laxmi928",
    LeetcodeLink: "https://leetcode.com/u/laxmi0425/",
  },
  {
    id: 18,
    name: "Aryan",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/aryan_pant.jpg",
    LinkedinLink: "https://www.linkedin.com/in/aryan-pant-61721240b",
    GithubLink: "https://github.com/aryanpant90",
    LeetcodeLink: "https://leetcode.com/u/aryan_pant/",
  },
  {
    id: 19,
    name: "Krishnam",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/krishnam_sharma.jpg",
    LinkedinLink: "https://www.linkedin.com/in/krishnam-sharma-00b3b2203",
    GithubLink: "https://github.com/krishnam1908",
    LeetcodeLink: "https://leetcode.com/u/krishnam190/",
  },
  {
    id: 20,
    name: "Anubhav",
    position: "",
    category: "Junior Council",
    image: "/assets/team-photos/junior-council/anubhav_sharma.jpg",
    LinkedinLink: "https://www.linkedin.com/in/anubhav-sharma-865066383",
    GithubLink: "https://github.com/anubhav-1921",
    LeetcodeLink: "https://leetcode.com/u/anubhavsh_21/",
  },
];

export const allTeamMembers: TeamMember[] = [
  ...seniorCouncil,
  ...juniorCouncil,
];
